let Projects = [
    {
        id: 1,
        name: "Clickamajiggy",
        description: "An interactive memory game featuring renowned works of art",
        deployLink: "https://jenjayme.github.io/clickamajiggy/",
        repoLink: "https://github.com/JenJayme/clickamajiggy",
        builtWith: "Javascript, React, React-Boostrap, Node.js & Express.js",
        photo: "clickamajiggy.png",
    }, {
        id: 2,
        name: "Employee Directory",
        description: "A react-based employee directory featuring the cast of the hit show Parks and Recreation",
        deployLink: "https://obscure-escarpment-21392.herokuapp.com/",
        repoLink: "https://github.com/JenJayme/employee-directory",
        builtWith: "Javascript, React, React-Boostrap, Node.js & Express.js",
        photo: "employeedir.png",
    }, {
        id: 3,
        name: "Bragging Rights: Call of Duty",
        description: "A platform for gamers to organize multi-game tournaments of friends playing Call of Duty",
        deployLink: "https://obscure-escarpment-21392.herokuapp.com/",
        repoLink: "https://github.com/seyouny/StatsDash",
        builtWith: "Javascript, React, React-Boostrap, Node.js & Express.js",
        photo: "braggingrights.png",
    }, {
        id: 4,
        name: "Virtuous Circle",
        description: "A solution to promote sharing of surplus fresh food among local pantries, shelters, restaurants and caterers",
        deployLink: "https://jenjayme.github.io/Project1_CGJK/",
        repoLink: "https://github.com/JenJayme/virtuous-circle",
        builtWith: "Javascript, Handlebars, Materialize, Node.js & Express.js",
        photo: "virtuous-circle.png",
    }, {
        id: 5,
        name: "Project Miles",
        description: "An app to promote healthy choices for teens by gamifying their exercise and meal choices, featuring a Marvel Avengers theme",
        deployLink: "https://jenjayme.github.io/Project_Miles/",
        repoLink: "https://github.com/JenJayme/Project_Miles",
        builtWith: "Javascript, Materialize, Node.js & Express.js",
        photo: "project-miles.png",
    }, {
        id: 6,
        name: "Game of Thrones Quiz",
        description: "A trivia game centered on the blockbuster HBO series",
        deployLink: "https://jenjayme.github.io/quiz-game/",
        repoLink: "https://github.com/JenJayme/quiz-game",
        builtWith: "Javascript, Bootstrap, Node.js & Express.js",
        photo: "got-min.jpg",
    }, {
        id: 7,
        name: "Spartan Fitness Tracker",
        description: "An app to track workouts and progress while training for a Spartan Race",
        deployLink: "https://dashboard.heroku.com/apps/spartan-tracker",
        repoLink: "https://github.com/JenJayme/spartan-tracker",
        builtWith: "Javascript, Bootstrap, Node.js & Express.js",
        photo: "spartan.png",
    }, {
        id: 8,
        name: "Middle Ground",
        description: "A social media news aggregator that shines a light on differences in news streams shared in conservative and liberal news sources",
        deployLink: "https://dashboard.heroku.com/apps/spartan-tracker",
        repoLink: "https://github.com/JenJayme/spartan-tracker",
        builtWith: "Javascript, Bootstrap, Node.js & Express.js",
        photo: "middle-ground.png",
    },
]

export default Projects;